In [20]:
import numpy as np

In [21]:
num = [
      [1,2,3,4],
      [2,3,4,6],
      [8,4,6,7]
]

    

In [22]:
num_array = np.array(num)

In [23]:
num_array

array([[1, 2, 3, 4],
       [2, 3, 4, 6],
       [8, 4, 6, 7]])

In [24]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.linspace(4,8)

array([4.        , 4.08163265, 4.16326531, 4.24489796, 4.32653061,
       4.40816327, 4.48979592, 4.57142857, 4.65306122, 4.73469388,
       4.81632653, 4.89795918, 4.97959184, 5.06122449, 5.14285714,
       5.2244898 , 5.30612245, 5.3877551 , 5.46938776, 5.55102041,
       5.63265306, 5.71428571, 5.79591837, 5.87755102, 5.95918367,
       6.04081633, 6.12244898, 6.20408163, 6.28571429, 6.36734694,
       6.44897959, 6.53061224, 6.6122449 , 6.69387755, 6.7755102 ,
       6.85714286, 6.93877551, 7.02040816, 7.10204082, 7.18367347,
       7.26530612, 7.34693878, 7.42857143, 7.51020408, 7.59183673,
       7.67346939, 7.75510204, 7.83673469, 7.91836735, 8.        ])

In [34]:
me = np.random.randn(100)
            

In [35]:
np.max(me)

np.float64(2.988692529631372)

In [39]:
num = np.arange(2,50,2)

In [40]:
num

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [42]:
num.reshape(4,6)

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36],
       [38, 40, 42, 44, 46, 48]])

In [46]:
 num.argmax()

np.int64(23)

In [2]:
import numpy as np

In [6]:
array_2d = np.linspace(3,4)

In [7]:
array_2d

array([3.        , 3.02040816, 3.04081633, 3.06122449, 3.08163265,
       3.10204082, 3.12244898, 3.14285714, 3.16326531, 3.18367347,
       3.20408163, 3.2244898 , 3.24489796, 3.26530612, 3.28571429,
       3.30612245, 3.32653061, 3.34693878, 3.36734694, 3.3877551 ,
       3.40816327, 3.42857143, 3.44897959, 3.46938776, 3.48979592,
       3.51020408, 3.53061224, 3.55102041, 3.57142857, 3.59183673,
       3.6122449 , 3.63265306, 3.65306122, 3.67346939, 3.69387755,
       3.71428571, 3.73469388, 3.75510204, 3.7755102 , 3.79591837,
       3.81632653, 3.83673469, 3.85714286, 3.87755102, 3.89795918,
       3.91836735, 3.93877551, 3.95918367, 3.97959184, 4.        ])

In [5]:
array_2d.shape

(3, 4)

In [10]:
array = np.arange(1, 10)

In [11]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
array2 = array[0:5]

In [15]:
array2

array([1, 2, 3, 4, 5])

In [16]:
array[0:34] = 100
print(array)

[100 100 100 100 100 100 100 100 100]


In [17]:
array2

array([100, 100, 100, 100, 100])

In [18]:
array3 = array[0:8]

In [22]:
array3

array([100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
a[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [30]:
num = np.arange(1, 20)

In [31]:
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [32]:
num1 = [num < 8]

In [33]:
num1

[array([ True,  True,  True,  True,  True,  True,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False])]

In [34]:
num [num > 8]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
list = np.arange(0  , 11)

In [38]:
list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
list + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
import pandas as pd

In [41]:
num1 = np.random.randn(4,5)

In [42]:
num1

array([[-0.71915941, -1.38315577, -1.11831778,  0.01495072, -1.86407401],
       [-0.42981923, -1.42551344,  0.84653898, -1.22391834, -2.93485526],
       [-0.83285617,  0.20502925,  0.55715476, -1.3082007 ,  2.86876042],
       [ 1.08553617,  0.71102295, -0.84089435, -0.99991564,  0.04241907]])

In [46]:
df = pd.DataFrame(num1, index = ["a", "b", "c", "d"], columns = ["a", "b", "c", "d", "e"])

In [47]:
df

,a,b,c,d,e
a,-0.719159,-1.383156,-1.118318,0.014951,-1.864074
b,-0.429819,-1.425513,0.846539,-1.223918,-2.934855
c,-0.832856,0.205029,0.557155,-1.308201,2.868760
d,1.085536,0.711023,-0.840894,-0.999916,0.042419
